apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: webhook
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dp215/webhook:latest
            env:
              - name: CHANNEL_URL
                value: my-kafka-channel-channel-bsrbn.default.svc.cluster.local
